import { Composer, InputFile } from "grammy";
import type { Ctx } from "../bot.js";
import { inlineButton, inlineKeyboard } from "../toolkit/index.js";
import { requireAuthorized, adminChatId } from "../lib/access.js";
import { read, remove, write } from "../lib/store.js";
import { dateLabel, now } from "../lib/time.js";
import { begin } from "./create-start.js";

type TemplateName = string;
interface Draft { photo?: string; photoFingerprint?: string; fullName?: string; fields: string[]; template?: TemplateName; consent?: string; }
export interface Submission { id: string; uploader_id: number; timestamp: number; photo: string; photo_fingerprint: string; full_name: string; additional_fields: string[]; template_used: TemplateName; image_file_ref: string; consent_statement: string; flagged?: boolean; }

const CONSENT = "I confirm I have the right to create and use this ID-style image and will not use it for illegal purposes.";
const DAY = 24 * 60 * 60 * 1000;
const HALF_HOUR = 30 * 60 * 1000;

const composer = new Composer<Ctx>();
const flow = (ctx: Ctx): Record<string, unknown> => ctx.session as Record<string, unknown>;
const draft = (ctx: Ctx): Draft => (flow(ctx).idDraft as Draft | undefined) ?? { fields: [] };

async function chooseTemplate(ctx: Ctx): Promise<void> {
  flow(ctx).idStep = "template";
  const templates = (await read<string[]>("templates:index")) ?? ["simple", "corporate", "badge"];
  await write("templates:index", templates);
  for (const name of templates) {
    const key = `template:${name}`;
    if (!(await read(key))) {
      await write(key, { template_name: name, background: name, photo_placement: "left", text_styles: "professional" });
    }
  }
  await ctx.reply("Choose the ID layout.", { reply_markup: inlineKeyboard([
    ...templates.slice(0, 20).map((template, index) => [inlineButton(template, `create:template:${index}`)]),
  ]) });
}

function clean(value: string): string { return value.trim().replace(/\s+/g, " "); }

function summary(item: Draft): string {
  return ["Review this sample ID image:", `Name: ${item.fullName}`, `Layout: ${item.template}`, ...item.fields.map((field) => `Field: ${field}`)].join("\n");
}

function xml(value: string): string {
  return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function base64(bytes: Uint8Array): string {
  let text = "";
  for (let index = 0; index < bytes.length; index += 8192) text += String.fromCharCode(...bytes.subarray(index, index + 8192));
  return btoa(text);
}

async function idCard(ctx: Ctx, item: Draft): Promise<InputFile> {
  const token = typeof process !== "undefined" ? process.env.BOT_TOKEN : (ctx as Ctx & { env?: { BOT_TOKEN?: string } }).env?.BOT_TOKEN;
  if (!token || !item.photo) throw new Error("photo rendering is unavailable");
  const file = await ctx.api.getFile(item.photo);
  if (!file.file_path) throw new Error("photo file is unavailable");
  const response = await fetch(`https://api.telegram.org/file/bot${token}/${file.file_path}`);
  if (!response.ok) throw new Error("photo download failed");
  const photo = base64(new Uint8Array(await response.arrayBuffer()));
  const lines = [item.fullName ?? "", ...item.fields].slice(0, 7)
    .map((line, index) => `<text x="330" y="${150 + index * 55}" font-family="Arial, sans-serif" font-size="${index === 0 ? 32 : 22}" fill="#172033">${xml(line)}</text>`)
    .join("");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="560" viewBox="0 0 900 560"><rect width="900" height="560" fill="#f5f7fb"/><rect width="900" height="72" fill="#172033"/><text x="42" y="47" font-family="Arial, sans-serif" font-size="28" fill="#ffffff">${xml(item.template ?? "ID card")}</text><rect x="42" y="112" width="240" height="320" fill="#d9e1ef"/><image x="42" y="112" width="240" height="320" preserveAspectRatio="xMidYMid slice" href="data:image/jpeg;base64,${photo}"/>${lines}<g transform="rotate(-27 450 280)" opacity="0.42"><text x="55" y="315" font-family="Arial, sans-serif" font-weight="bold" font-size="64" fill="#c51d2e">SAMPLE — NOT A REAL ID</text></g><text x="450" y="530" text-anchor="middle" font-family="Arial, sans-serif" font-size="16" fill="#4b5563">Generated by BadgeMaker — For demonstration only</text></svg>`;
  return new InputFile(new TextEncoder().encode(svg), "id-card.svg");
}

async function rateLimit(userId: number, timestamp: number): Promise<string | undefined> {
  const suspension = await read<{ until: number }>(`suspension:${userId}`);
  if (suspension && suspension.until > timestamp) return "Your submissions are temporarily suspended because a safety limit was reached. Try again later.";
  const index = (await read<string[]>(`user-submissions:${userId}`)) ?? [];
  const kept: string[] = [];
  const recent: Submission[] = [];
  for (const id of index) {
    const submission = await read<Submission>(`submission:${id}`);
    if (submission) {
      kept.push(id);
      if (submission.timestamp > timestamp - DAY) recent.push(submission);
    }
  }
  await write(`user-submissions:${userId}`, kept);
  const last = recent.reduce((latest, submission) => Math.max(latest, submission.timestamp), 0);
  const until = recent.length >= 5 ? Math.min(...recent.map((submission) => submission.timestamp)) + DAY : last + HALF_HOUR;
  if (recent.length >= 5 || (last && timestamp < last + HALF_HOUR)) {
    await write(`suspension:${userId}`, { until });
    return recent.length >= 5 ? "You have reached the limit of five submissions in 24 hours. Your submissions are paused until the rolling window clears." : "Please wait 30 minutes between submissions. Your submissions are paused until then.";
  }
  return undefined;
}

async function checkAttemptVolume(ctx: Ctx, userId: number, timestamp: number): Promise<void> {
  const attempts = ((await read<number[]>(`submission-attempts:${userId}`)) ?? []).filter((at) => at > timestamp - DAY);
  attempts.push(timestamp);
  await write(`submission-attempts:${userId}`, attempts);
  if (attempts.length !== 21) return;
  const admin = adminChatId();
  if (admin) try { await ctx.api.sendMessage(admin, "Safety alert: one account attempted more than 20 submissions in 24 hours."); } catch { /* best-effort alert */ }
}

async function notifyAdmin(ctx: Ctx, submission: Submission, item: Draft): Promise<void> {
  const admin = adminChatId();
  if (!admin) return;
  const metadata = ["New public ID submission", summary(item), `Consent: ${CONSENT}`, `Audit date: ${dateLabel(submission.timestamp)}`].join("\n");
  try {
    await ctx.api.sendDocument(admin, submission.image_file_ref, {
      caption: metadata,
      reply_markup: inlineKeyboard([[inlineButton("Report user", `report:${submission.id}`)]]),
    });
  } catch { /* Admin delivery is best-effort and must not lose the audit record. */ }
}

async function checkPhotoPattern(ctx: Ctx, submission: Submission): Promise<void> {
  const observations = ((await read<Array<{ userId: number; timestamp: number }>>(`photo-observations:${submission.photo_fingerprint}`)) ?? [])
    .filter((observation) => observation.timestamp > submission.timestamp - DAY);
  if (!observations.some((observation) => observation.userId === submission.uploader_id)) observations.push({ userId: submission.uploader_id, timestamp: submission.timestamp });
  await write(`photo-observations:${submission.photo_fingerprint}`, observations);
  if (observations.length === 11) {
    const admin = adminChatId();
    if (admin) try { await ctx.api.sendMessage(admin, "Safety alert: more than 10 accounts submitted the same photo in the last review set."); } catch { /* best-effort alert */ }
  }
}

composer.command("create", async (ctx) => { await begin(ctx); });

composer.command("cancel", async (ctx) => {
  const state = flow(ctx);
  delete state.idStep;
  delete state.idDraft;
  await ctx.reply("ID creation was cancelled. You can start again from the menu.");
});

composer.on("message:photo", async (ctx, next) => {
  if (flow(ctx).idStep !== "photo") return next();
  if (!(await requireAuthorized(ctx))) return;
  const photos = ctx.message.photo;
  const item: Draft = { fields: [] };
  item.photo = photos[photos.length - 1].file_id;
  item.photoFingerprint = photos[photos.length - 1].file_unique_id;
  flow(ctx).idDraft = item;
  flow(ctx).idStep = "name";
  await ctx.reply("Enter the full name exactly as it should appear.", { reply_markup: { force_reply: true, input_field_placeholder: "Full name" } });
});

composer.on("message:document", async (ctx, next) => {
  if (flow(ctx).idStep !== "photo") return next();
  await ctx.reply("That file isn't a photo. Send the image as a Telegram photo.");
});

composer.on("message:text", async (ctx, next) => {
  const state = flow(ctx);
  const step = state.idStep;
  if (step !== "name" && step !== "field") return next();
  if (!(await requireAuthorized(ctx))) return;
  const value = clean(ctx.message.text);
  if (step === "name") {
    if (value.length < 2 || value.length > 120) {
      await ctx.reply("Enter a full name between 2 and 120 characters.");
      return;
    }
    const item = draft(ctx);
    item.fullName = value;
    state.idDraft = item;
    state.idStep = "fields";
    await ctx.reply("Add an optional field, or continue without one.", { reply_markup: inlineKeyboard([
      [inlineButton("Add field", "create:field:add"), inlineButton("Choose layout", "create:fields:done")],
    ]) });
    return;
  }
  const item = draft(ctx);
  if (!value.includes(":") || value.length > 160) {
    await ctx.reply("Use a short label and value, for example: Department: Operations.");
    return;
  }
  if (item.fields.length >= 6) {
    await ctx.reply("You can add up to six optional fields. Choose the layout to continue.");
    state.idStep = "fields";
    return;
  }
  item.fields.push(value);
  state.idDraft = item;
  state.idStep = "fields";
  await ctx.reply(`Field ${item.fields.length} added. Add another field or choose the layout.`, { reply_markup: inlineKeyboard([
    [inlineButton("Add field", "create:field:add"), inlineButton("Choose layout", "create:fields:done")],
  ]) });
});

composer.callbackQuery("create:field:add", async (ctx) => {
  await ctx.answerCallbackQuery();
  if (!(await requireAuthorized(ctx))) return;
  if (draft(ctx).fields.length >= 6) { await ctx.reply("You can add up to six optional fields. Choose the layout to continue."); return; }
  flow(ctx).idStep = "field";
  await ctx.reply("Enter one field as Label: value.", { reply_markup: { force_reply: true, input_field_placeholder: "Department: Operations" } });
});

composer.callbackQuery("create:fields:done", async (ctx) => { await ctx.answerCallbackQuery(); if (await requireAuthorized(ctx)) await chooseTemplate(ctx); });

composer.callbackQuery(/^create:template:(\d+)$/, async (ctx) => {
  await ctx.answerCallbackQuery();
  if (!(await requireAuthorized(ctx))) return;
  const templates = (await read<string[]>("templates:index")) ?? ["simple", "corporate", "badge"];
  const template = templates[Number(ctx.match[1])];
  if (!template) { await ctx.reply("That layout is no longer available. Choose a layout again."); return; }
  const item = draft(ctx);
  item.template = template;
  flow(ctx).idDraft = item;
  flow(ctx).idStep = "consent";
  await ctx.reply(`${summary(item)}\n\n${CONSENT}`, { reply_markup: inlineKeyboard([[inlineButton("I confirm", "create:consent:yes")], [inlineButton("Cancel", "create:confirm:no")]]) });
});

composer.callbackQuery("create:consent:yes", async (ctx) => {
  await ctx.answerCallbackQuery();
  if (!(await requireAuthorized(ctx))) return;
  if (flow(ctx).idStep !== "consent") { await ctx.reply("Your draft is no longer available. Start a new ID from the menu."); return; }
  const item = draft(ctx);
  item.consent = CONSENT;
  flow(ctx).idDraft = item;
  flow(ctx).idStep = "confirm";
  await ctx.reply("Consent recorded. Submit this watermarked sample ID image when you are ready.", { reply_markup: inlineKeyboard([[inlineButton("Submit ID", "create:confirm:yes"), inlineButton("Cancel", "create:confirm:no")]]) });
});

composer.callbackQuery("create:confirm:no", async (ctx) => {
  await ctx.answerCallbackQuery();
  delete flow(ctx).idStep;
  delete flow(ctx).idDraft;
  await ctx.reply("ID creation was cancelled. You can start again from the menu.");
});

composer.callbackQuery("create:confirm:yes", async (ctx) => {
  await ctx.answerCallbackQuery();
  if (!(await requireAuthorized(ctx))) return;
  const item = draft(ctx);
  if (!ctx.from || !item.photo || !item.photoFingerprint || !item.fullName || !item.template || item.consent !== CONSENT) { await ctx.reply("Your draft is incomplete or missing consent. Start a new ID from the menu."); return; }
  const timestamp = now().getTime();
  await checkAttemptVolume(ctx, ctx.from.id, timestamp);
  const blocked = await rateLimit(ctx.from.id, timestamp);
  if (blocked) { await ctx.reply(blocked); return; }
  const id = `${ctx.from.id}-${timestamp}`;
  let generated;
  try {
    generated = await ctx.replyWithDocument(await idCard(ctx, item), { caption: summary(item) });
  } catch {
    await ctx.reply("Couldn't create the ID image right now. Check the photo and try again.");
    return;
  }
  const imageFileRef = generated.document?.file_id;
  if (!imageFileRef) { await ctx.reply("Couldn't save the ID image. Try again."); return; }
  const submission: Submission = { id, uploader_id: ctx.from.id, timestamp, photo: item.photo, photo_fingerprint: item.photoFingerprint, full_name: item.fullName, additional_fields: item.fields, template_used: item.template, image_file_ref: imageFileRef, consent_statement: CONSENT };
  await write(`submission:${id}`, submission);
  const index = (await read<string[]>("submissions:index")) ?? [];
  const retention = (await read<{ retentionDays?: number }>("settings"))?.retentionDays ?? 90;
  const cutoff = timestamp - retention * 86400000;
  const retained: string[] = [];
  for (const existingId of index) {
    const existing = await read<Submission>(`submission:${existingId}`);
    if (!existing || existing.timestamp < cutoff) await remove(`submission:${existingId}`);
    else retained.push(existingId);
  }
  retained.push(id);
  await write("submissions:index", retained);
  const userIndex = (await read<string[]>(`user-submissions:${ctx.from.id}`)) ?? [];
  userIndex.push(id);
  await write(`user-submissions:${ctx.from.id}`, userIndex);
  await checkPhotoPattern(ctx, submission);
  await notifyAdmin(ctx, submission, item);
  delete flow(ctx).idStep;
  delete flow(ctx).idDraft;
  await ctx.reply(adminChatId() ? "Your watermarked sample ID image is ready and has been sent for review." : "Your watermarked sample ID image is ready. Admin review isn't set up yet.");
});

export default composer;
